# 赞助支持 OneBots
# 
# 支付宝/微信二维码请查看 README.md 中的赞助区
# QR codes for Alipay/WeChat are available in README.md

github: lc-cn
custom:
  - https://afdian.net/a/lc-cn
  - https://github.com/lc-cn/onebots#-赞助支持
